const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  checkPath: (path) => ipcRenderer.invoke('check-path', path),
  getMods: (path) => ipcRenderer.invoke('get-mods', path),
  selectDirectory: () => ipcRenderer.invoke('select-directory'),
  loginXPlaneOrg: () => ipcRenderer.invoke('login-xplane-org'),
  loginXPlaneTo: () => ipcRenderer.invoke('login-xplane-to'),
  downloadAndInstallMod: (args) => ipcRenderer.invoke('download-and-install-mod', args),
  downloadInteractive: (args) => ipcRenderer.invoke('download-interactive', args),
  toggleMod: (args) => ipcRenderer.invoke('toggle-mod', args),
  openFolder: (path) => ipcRenderer.invoke('open-folder', path),
  launchGame: (path) => ipcRenderer.invoke('launch-game', path),
  getCustomCatalog: (path) => ipcRenderer.invoke('get-custom-catalog', path),
  saveCustomCatalog: (args) => ipcRenderer.invoke('save-custom-catalog', args),
  fetchModMetadata: (args) => ipcRenderer.invoke('fetch-mod-metadata', args),
  updateScreenshotSettings: (args) => ipcRenderer.invoke('update-screenshot-settings', args),
  getScreenshots: (args) => ipcRenderer.invoke('get-screenshots', args),
  startScreenshotService: (args) => ipcRenderer.invoke('start-screenshot-service', args),
  onScreenshotCaptured: (callback) => ipcRenderer.on('screenshot-captured', (event, meta) => callback(meta)),
  onScreenshotsUpdated: (callback) => ipcRenderer.on('screenshots-updated', () => callback()),
  deleteMod: (args) => ipcRenderer.invoke('delete-mod', args),
  deleteCustomAddon: (args) => ipcRenderer.invoke('delete-custom-addon', args),
  getUnifiedFeed: () => ipcRenderer.invoke('get-unified-feed'),
  openArticle: (url) => ipcRenderer.invoke('open-article', url),
  onDownloadProgress: (callback) => ipcRenderer.on('download-progress', (event, data) => callback(data)),
  onUpdateAvailable: (callback) => ipcRenderer.on("update-available", (event, info) => callback(info)),
  onUpdateDownloadProgress: (callback) => ipcRenderer.on("update-download-progress", (event, progress) => callback(progress)),
  onUpdateDownloaded: (callback) => ipcRenderer.on("update-downloaded", () => callback()),
  downloadUpdate: () => ipcRenderer.invoke("download-update"),
  installUpdate: () => ipcRenderer.invoke("install-update"),
  getChangelog: () => ipcRenderer.invoke('get-changelog'),
  getAppVersion: () => ipcRenderer.invoke('get-app-version'),
  getWishlist: (path) => ipcRenderer.invoke('get-wishlist', path),
  saveWishlist: (args) => ipcRenderer.invoke('save-wishlist', args),
  startWishlistMonitor: (path) => ipcRenderer.invoke('start-wishlist-monitor', path),
});
